#packages
from flask import Blueprint, render_template

#plots 
import plotly.express as px

#data 
import pandas as pd
import numpy as np

#utils
from .utils import get_unioned_data_from

views = Blueprint("views", __name__)

@views.route('/stargate')
async def home():
    return render_template("tab-stargate.html", page="home")

@views.route('/squid')
async def squid():
    return render_template("tab-squid.html", page="squid")

@views.route('/satellite')
async def satellite():
    return render_template("tab-satellite.html", page="satellite")

@views.route('/comparison')
async def comparison():
    return render_template("tab-key-differences.html", page="differences")

@views.route('/')
async def overview():
    return render_template("tab-overview.html", page="overview")

@views.route('/sql')
async def sql():
    return render_template("tab-sql.html", page="sql")

# @views.route('/predictive')
# async def predicitve():
#     columns = "ACROSS_TOTAL_AMOUNT_USD_BRIDGED,ACROSS_ETH_AMOUNT_USD_BRIDGED,ACROSS_ETH_TX_COUNT,ACROSS_BSC_AMOUNT_USD_BRIDGED,ACROSS_BSC_TX_COUNT,ACROSS_AVALANCHE_AMOUNT_USD_BRIDGED,ACROSS_AVALANCHE_TX_COUNT,ACROSS_OPTIMISM_AMOUNT_USD_BRIDGED,ACROSS_OPTIMISM_TX_COUNT,ACROSS_ARBITRUM_AMOUNT_USD_BRIDGED,ACROSS_ARBITRUM_TX_COUNT,ACROSS_POLYGON_AMOUNT_USD_BRIDGED,ACROSS_POLYGON_TX_COUNT,ACROSS_DAYS_ACTIVE,ACROSS_TOTAL_TX_COUNT,SQUID_TOTAL_AMOUNT_USD_BRIDGED,SQUID_ETH_AMOUNT_USD_BRIDGED,SQUID_ETH_TX_COUNT,SQUID_BSC_AMOUNT_USD_BRIDGED,SQUID_BSC_TX_COUNT,SQUID_AVALANCHE_AMOUNT_USD_BRIDGED,SQUID_AVALANCHE_TX_COUNT,SQUID_OPTIMISM_AMOUNT_USD_BRIDGED,SQUID_OPTIMISM_TX_COUNT,SQUID_ARBITRUM_AMOUNT_USD_BRIDGED,SQUID_ARBITRUM_TX_COUNT,SQUID_POLYGON_AMOUNT_USD_BRIDGED,SQUID_POLYGON_TX_COUNT,SQUID_DAYS_ACTIVE,SQUID_TOTAL_TX_COUNT,BSC_AGE_DAY,BSC_TX_COUNT,CELER_TOTAL_AMOUNT_USD_BRIDGED,CELER_ETH_AMOUNT_USD_BRIDGED,CELER_ETH_TX_COUNT,CELER_BSC_AMOUNT_USD_BRIDGED,CELER_BSC_TX_COUNT,CELER_AVALANCHE_AMOUNT_USD_BRIDGED,CELER_AVALANCHE_TX_COUNT,CELER_OPTIMISM_AMOUNT_USD_BRIDGED,CELER_OPTIMISM_TX_COUNT,CELER_ARBITRUM_AMOUNT_USD_BRIDGED,CELER_ARBITRUM_TX_COUNT,CELER_POLYGON_AMOUNT_USD_BRIDGED,CELER_POLYGON_TX_COUNT,CELER_DAYS_ACTIVE,CELER_TOTAL_TX_COUNT,TOTAL_SWAP_AMOUNT_USD,AVERAGE_SWAP_AMOUNT_USD_PER_TX,MEDIAN_SWAP_AMOUNT_USD_PER_TX,UNISWAP_SWAP_VOLUME,CURVE_SWAP_VOLUME,OTHER_SWAP_VOLUME,SWAP_DAYS_ACTIVE,SWAP_TX_COUNT,ETH_AGE_DAY,ETH_TX_COUNT,AVALANCHE_AGE_DAY,AVALANCHE_TX_COUNT,OPTIMISM_AGE_DAY,OPTIMISM_TX_COUNT,ARBITRUM_AGE_DAY,ARBITRUM_TX_COUNT,POLYGON_AGE_DAY,POLYGON_TX_COUNT,WORMHOLE_TOTAL_AMOUNT_USD_BRIDGED,WORMHOLE_ETH_AMOUNT_USD_BRIDGED,WORMHOLE_ETH_TX_COUNT,WORMHOLE_BSC_AMOUNT_USD_BRIDGED,WORMHOLE_BSC_TX_COUNT,WORMHOLE_AVALANCHE_AMOUNT_USD_BRIDGED,WORMHOLE_AVALANCHE_TX_COUNT,WORMHOLE_OPTIMISM_AMOUNT_USD_BRIDGED,WORMHOLE_OPTIMISM_TX_COUNT,WORMHOLE_ARBITRUM_AMOUNT_USD_BRIDGED,WORMHOLE_ARBITRUM_TX_COUNT,WORMHOLE_POLYGON_AMOUNT_USD_BRIDGED,WORMHOLE_POLYGON_TX_COUNT,WORMHOLE_DAYS_ACTIVE,WORMHOLE_TOTAL_TX_COUNT,MULTICHAIN_TOTAL_AMOUNT_USD_BRIDGED,MULTICHAIN_ETH_AMOUNT_USD_BRIDGED,MULTICHAIN_ETH_TX_COUNT,MULTICHAIN_BSC_AMOUNT_USD_BRIDGED,MULTICHAIN_BSC_TX_COUNT,MULTICHAIN_AVALANCHE_AMOUNT_USD_BRIDGED,MULTICHAIN_AVALANCHE_TX_COUNT,MULTICHAIN_OPTIMISM_AMOUNT_USD_BRIDGED,MULTICHAIN_OPTIMISM_TX_COUNT,MULTICHAIN_ARBITRUM_AMOUNT_USD_BRIDGED,MULTICHAIN_ARBITRUM_TX_COUNT,MULTICHAIN_POLYGON_AMOUNT_USD_BRIDGED,MULTICHAIN_POLYGON_TX_COUNT,MULTICHAIN_DAYS_ACTIVE,MULTICHAIN_TOTAL_TX_COUNT,HOP_TOTAL_AMOUNT_USD_BRIDGED,HOP_ETH_AMOUNT_USD_BRIDGED,HOP_ETH_TX_COUNT,HOP_BSC_AMOUNT_USD_BRIDGED,HOP_BSC_TX_COUNT,HOP_AVALANCHE_AMOUNT_USD_BRIDGED,HOP_AVALANCHE_TX_COUNT,HOP_OPTIMISM_AMOUNT_USD_BRIDGED,HOP_OPTIMISM_TX_COUNT,HOP_ARBITRUM_AMOUNT_USD_BRIDGED,HOP_ARBITRUM_TX_COUNT,HOP_POLYGON_AMOUNT_USD_BRIDGED,HOP_POLYGON_TX_COUNT,HOP_DAYS_ACTIVE,HOP_TOTAL_TX_COUNT,SYNAPSE_TOTAL_AMOUNT_USD_BRIDGED,SYNAPSE_ETH_AMOUNT_USD_BRIDGED,SYNAPSE_ETH_TX_COUNT,SYNAPSE_BSC_AMOUNT_USD_BRIDGED,SYNAPSE_BSC_TX_COUNT,SYNAPSE_AVALANCHE_AMOUNT_USD_BRIDGED,SYNAPSE_AVALANCHE_TX_COUNT,SYNAPSE_OPTIMISM_AMOUNT_USD_BRIDGED,SYNAPSE_OPTIMISM_TX_COUNT,SYNAPSE_ARBITRUM_AMOUNT_USD_BRIDGED,SYNAPSE_ARBITRUM_TX_COUNT,SYNAPSE_POLYGON_AMOUNT_USD_BRIDGED,SYNAPSE_POLYGON_TX_COUNT,SYNAPSE_DAYS_ACTIVE,SYNAPSE_TOTAL_TX_COUNT,STARGATE_TOTAL_AMOUNT_USD_BRIDGED,STARGATE_ETH_AMOUNT_USD_BRIDGED,STARGATE_ETH_TX_COUNT,STARGATE_BSC_AMOUNT_USD_BRIDGED,STARGATE_BSC_TX_COUNT,STARGATE_AVALANCHE_AMOUNT_USD_BRIDGED,STARGATE_AVALANCHE_TX_COUNT,STARGATE_OPTIMISM_AMOUNT_USD_BRIDGED,STARGATE_OPTIMISM_TX_COUNT,STARGATE_ARBITRUM_AMOUNT_USD_BRIDGED,STARGATE_ARBITRUM_TX_COUNT,STARGATE_POLYGON_AMOUNT_USD_BRIDGED,STARGATE_POLYGON_TX_COUNT,STARGATE_DAYS_ACTIVE,STARGATE_TOTAL_TX_COUNT,CONNEXT_TOTAL_AMOUNT_USD_BRIDGED,CONNEXT_ETH_AMOUNT_USD_BRIDGED,CONNEXT_ETH_TX_COUNT,CONNEXT_BSC_AMOUNT_USD_BRIDGED,CONNEXT_BSC_TX_COUNT,CONNEXT_AVALANCHE_AMOUNT_USD_BRIDGED,CONNEXT_AVALANCHE_TX_COUNT,CONNEXT_OPTIMISM_AMOUNT_USD_BRIDGED,CONNEXT_OPTIMISM_TX_COUNT,CONNEXT_ARBITRUM_AMOUNT_USD_BRIDGED,CONNEXT_ARBITRUM_TX_COUNT,CONNEXT_POLYGON_AMOUNT_USD_BRIDGED,CONNEXT_POLYGON_TX_COUNT,CONNEXT_DAYS_ACTIVE,CONNEXT_TOTAL_TX_COUNT,SATELLITE_TOTAL_AMOUNT_USD_BRIDGED,SATELLITE_ETH_AMOUNT_USD_BRIDGED,SATELLITE_ETH_TX_COUNT,SATELLITE_BSC_AMOUNT_USD_BRIDGED,SATELLITE_BSC_TX_COUNT,SATELLITE_AVALANCHE_AMOUNT_USD_BRIDGED,SATELLITE_AVALANCHE_TX_COUNT,SATELLITE_OPTIMISM_AMOUNT_USD_BRIDGED,SATELLITE_OPTIMISM_TX_COUNT,SATELLITE_ARBITRUM_AMOUNT_USD_BRIDGED,SATELLITE_ARBITRUM_TX_COUNT,SATELLITE_POLYGON_AMOUNT_USD_BRIDGED,SATELLITE_POLYGON_TX_COUNT,SATELLITE_DAYS_ACTIVE,SATELLITE_TOTAL_TX_COUNT,TOTAL_AMOUNT_USD_BRIDGED,ETH_AMOUNT_USD_BRIDGED,OPTIMISM_AMOUNT_USD_BRIDGED,ARBITRUM_AMOUNT_USD_BRIDGED,AVALANCHE_AMOUNT_USD_BRIDGED,BSC_AMOUNT_USD_BRIDGED,POLYGON_AMOUNT_USD_BRIDGED,BRIDGES_USED".split(",")
#     columns.sort()

#     predict_columns = [
#         'BSC_AGE_DAY',
#         'BSC_TX_COUNT',
#         'ETH_AGE_DAY',
#         'ETH_TX_COUNT',
#         'AVALANCHE_AGE_DAY',
#         'AVALANCHE_TX_COUNT',
#         'OPTIMISM_AGE_DAY',
#         'OPTIMISM_TX_COUNT',
#         'ARBITRUM_AGE_DAY',
#         'ARBITRUM_TX_COUNT',
#         'POLYGON_AGE_DAY',
#         'POLYGON_TX_COUNT',
#         'TOTAL_AMOUNT_USD_BRIDGED',
#         'ETH_AMOUNT_USD_BRIDGED',
#         'OPTIMISM_AMOUNT_USD_BRIDGED',
#         'ARBITRUM_AMOUNT_USD_BRIDGED',
#         'AVALANCHE_AMOUNT_USD_BRIDGED',
#         'BSC_AMOUNT_USD_BRIDGED',
#         'POLYGON_AMOUNT_USD_BRIDGED',
#         'TOTAL_SWAP_AMOUNT_USD',
#         'AVERAGE_SWAP_AMOUNT_USD_PER_TX',
#         'MEDIAN_SWAP_AMOUNT_USD_PER_TX',
#         'UNISWAP_SWAP_VOLUME',
#         'CURVE_SWAP_VOLUME',
#         'OTHER_SWAP_VOLUME',
#         'SWAP_DAYS_ACTIVE',
#         'SWAP_TX_COUNT',
#         'BRIDGES_USED',
#     ]
#     return render_template("predictive.html", page="predictive", columns=columns, predict_columns=predict_columns)